<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pizzeria extends \App\Entity\Pizzeria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'id_pizzeria', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'marge', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'numTelephone', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'pizzaiolos', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'pizzas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'id_pizzeria', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'marge', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'numTelephone', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'pizzaiolos', '' . "\0" . 'App\\Entity\\Pizzeria' . "\0" . 'pizzas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pizzeria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdPizzeria(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPizzeria', []);

        return parent::getIdPizzeria();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPizzeria(int $id_pizzeria): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPizzeria', [$id_pizzeria]);

        return parent::setIdPizzeria($id_pizzeria);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarge(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarge', []);

        return parent::getMarge();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarge(float $marge): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarge', [$marge]);

        return parent::setMarge($marge);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTelephone', []);

        return parent::getNumTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTelephone(string $numTelephone): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTelephone', [$numTelephone]);

        return parent::setNumTelephone($numTelephone);
    }

    /**
     * {@inheritDoc}
     */
    public function addPizzaiolo(\App\Entity\Pizzaiolo $pizzaiolo): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPizzaiolo', [$pizzaiolo]);

        return parent::addPizzaiolo($pizzaiolo);
    }

    /**
     * {@inheritDoc}
     */
    public function removePizzaiolo(\App\Entity\Pizzaiolo $pizzaiolo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePizzaiolo', [$pizzaiolo]);

        parent::removePizzaiolo($pizzaiolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPizzaiolos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPizzaiolos', []);

        return parent::getPizzaiolos();
    }

    /**
     * {@inheritDoc}
     */
    public function getPizzas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPizzas', []);

        return parent::getPizzas();
    }

    /**
     * {@inheritDoc}
     */
    public function addPizza(\App\Entity\Pizza $pizza): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPizza', [$pizza]);

        return parent::addPizza($pizza);
    }

    /**
     * {@inheritDoc}
     */
    public function removePizza(\App\Entity\Pizza $pizza): \App\Entity\Pizzeria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePizza', [$pizza]);

        return parent::removePizza($pizza);
    }

}
