<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2iiBVgl' shared service.

return $this->privates['.service_locator.2iiBVgl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pizzaDao' => ['privates', 'App\\Service\\Dao\\PizzaDao', 'getPizzaDaoService.php', true],
], [
    'pizzaDao' => 'App\\Service\\Dao\\PizzaDao',
]);
