<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Dao\PizzeriaDao' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Dao/PizzeriaDao.php';

return $this->privates['App\\Service\\Dao\\PizzeriaDao'] = new \App\Service\Dao\PizzeriaDao(($this->privates['App\\Repository\\PizzeriaRepository'] ?? $this->load('getPizzeriaRepositoryService.php')));
