<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cEUu85H' shared service.

return $this->privates['.service_locator.cEUu85H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pizzaDao' => ['privates', 'App\\Service\\Dao\\PizzaDao', 'getPizzaDaoService.php', true],
    'pizzeriaDao' => ['privates', 'App\\Service\\Dao\\PizzeriaDao', 'getPizzeriaDaoService.php', true],
], [
    'pizzaDao' => 'App\\Service\\Dao\\PizzaDao',
    'pizzeriaDao' => 'App\\Service\\Dao\\PizzeriaDao',
]);
