<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PizzaController::detailAction' => ['privates', '.service_locator.2iiBVgl', 'get_ServiceLocator_2iiBVglService.php', true],
    'App\\Controller\\PizzaController::listeAction' => ['privates', '.service_locator.2iiBVgl', 'get_ServiceLocator_2iiBVglService.php', true],
    'App\\Controller\\PizzaioloController::disponiblesAction' => ['privates', '.service_locator._kc04ax', 'get_ServiceLocator_Kc04axService.php', true],
    'App\\Controller\\PizzeriaController::detailAction' => ['privates', '.service_locator.cEUu85H', 'get_ServiceLocator_CEUu85HService.php', true],
    'App\\Controller\\PizzeriaController::listeAction' => ['privates', '.service_locator.b8GLnfQ', 'get_ServiceLocator_B8GLnfQService.php', true],
    'App\\Controller\\PizzaController:detailAction' => ['privates', '.service_locator.2iiBVgl', 'get_ServiceLocator_2iiBVglService.php', true],
    'App\\Controller\\PizzaController:listeAction' => ['privates', '.service_locator.2iiBVgl', 'get_ServiceLocator_2iiBVglService.php', true],
    'App\\Controller\\PizzaioloController:disponiblesAction' => ['privates', '.service_locator._kc04ax', 'get_ServiceLocator_Kc04axService.php', true],
    'App\\Controller\\PizzeriaController:detailAction' => ['privates', '.service_locator.cEUu85H', 'get_ServiceLocator_CEUu85HService.php', true],
    'App\\Controller\\PizzeriaController:listeAction' => ['privates', '.service_locator.b8GLnfQ', 'get_ServiceLocator_B8GLnfQService.php', true],
], [
    'App\\Controller\\PizzaController::detailAction' => '?',
    'App\\Controller\\PizzaController::listeAction' => '?',
    'App\\Controller\\PizzaioloController::disponiblesAction' => '?',
    'App\\Controller\\PizzeriaController::detailAction' => '?',
    'App\\Controller\\PizzeriaController::listeAction' => '?',
    'App\\Controller\\PizzaController:detailAction' => '?',
    'App\\Controller\\PizzaController:listeAction' => '?',
    'App\\Controller\\PizzaioloController:disponiblesAction' => '?',
    'App\\Controller\\PizzeriaController:detailAction' => '?',
    'App\\Controller\\PizzeriaController:listeAction' => '?',
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
