<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Dao\PizzaDao' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Dao/PizzaDao.php';

return $this->privates['App\\Service\\Dao\\PizzaDao'] = new \App\Service\Dao\PizzaDao(($this->privates['App\\Repository\\PizzaRepository'] ?? $this->load('getPizzaRepositoryService.php')));
