<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Dao\PizzaioloDao' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Dao/PizzaioloDao.php';

return $this->privates['App\\Service\\Dao\\PizzaioloDao'] = new \App\Service\Dao\PizzaioloDao(($this->privates['App\\Repository\\PizzaioloRepository'] ?? $this->load('getPizzaioloRepositoryService.php')));
